#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Sdz\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username
            #entity: { class: Sdz\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
         
        main_login:
            pattern:  ^/login$
            anonymous: true
            
        main:
            pattern:  ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /blog
            logout:
                path: fos_user_security_logout
                target: /blog
            remember_me:
                key: %secret%



        
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN, ip: 127.0.0.1, requires_channel: https }
       
