sdz_blog_homepage:
    pattern:  /{page}
    defaults: { _controller: SdzBlogBundle:Blog:index, page: 1 }
    requirements: 
        page: \d*

sdz_blog_suiteip:
    pattern:  /suiteip/{page}
    defaults: { _controller: SdzBlogBundle:Blog:suiteip, page: 1 }
    requirements: 
        page: \d*
        
sdz_blog_contact:
    pattern:  /contact/{page}
    defaults: { _controller: SdzBlogBundle:Blog:contact, page: 1 }
    requirements: 
        page: \d*

sdz_blog_ftic:
    pattern:  /ftic/{page}
    defaults: { _controller: SdzBlogBundle:Blog:ftic, page: 1 }
    requirements: 
        page: \d*

sdz_blog_fbureau:
    pattern:  /fbureautic/{page}
    defaults: { _controller: SdzBlogBundle:Blog:fbureau, page: 1 }
    requirements: 
        page: \d*
        
sdz_blog_jerry:
    pattern:  /jerry/{page}
    defaults: { _controller: SdzBlogBundle:Blog:jerry, page: 1 }
    requirements:
        page: \d*
        
sdz_blog_sante:
    pattern:  /sante/{page}
    defaults: { _controller: SdzBlogBundle:Blog:sante, page: 1 }
    requirements:
        page: \d*

sdz_blog_osm:
    pattern:  /osm/{page}
    defaults: { _controller: SdzBlogBundle:Blog:osm, page: 1 }
    requirements:
        page: \d*

sdz_blog_contextsahel:
    pattern:  /contextsahel/{page}
    defaults: { _controller: SdzBlogBundle:Blog:contextsahel, page: 1 }
    requirements:
        page: \d*

sdz_blog_equipe:
    pattern:  /equipe/{page}
    defaults: { _controller: SdzBlogBundle:Blog:equipe, page: 1 }
    requirements:
        page: \d*
        
sdz_blog_mobile:
    pattern:  /mobile/{page}
    defaults: { _controller: SdzBlogBundle:Blog:mobile, page: 1 }
    requirements:
        page: \d*

         

